#!/bin/sh
##
## Sanity check
##
if [[ ! "$(lsb_release -d | cut -f2)" =~ $'Ubuntu 14.04' ]]; then
   echo "This script is only known to work on Ubuntu 14.04, exiting...";
   exit;
fi

##
## Change ubuntu repo
##
## mirrors.ustc.edu.cn
## cn.archive.ubuntu.com
sudo cp  /etc/apt/sources.list  /etc/apt/sources.list.bak
sudo sed -i 's/security.ubuntu.com/mirrors.ustc.edu.cn/g' /etc/apt/sources.list
sudo sed -i 's/cn.archive.ubuntu.com/mirrors.ustc.edu.cn/g' /etc/apt/sources.list
sudo sed -i 's/us.archive.ubuntu.com/mirrors.ustc.edu.cn/g' /etc/apt/sources.list
##
## Install docker
##
sudo apt-get update
sudo apt-get install docker.io
##
## Pre setup
##
sudo docker pull phusion/baseimage
git clone https://github.com/eduStack/configuration.git -b docker_release ~/configuration
sudo docker run -i -t -d -v ~/configuration:/configuration phusion/baseimage /sbin/my_init --enable-insecure-key
ID=$(sudo docker ps | cut -c1-20 | awk 'NR==2 {print}')
IP=$(sudo docker inspect -f "{{ .NetworkSettings.IPAddress }}" $ID)
curl -o insecure_key -fSL https://github.com/phusion/baseimage-docker/raw/master/image/insecure_key
chmod 600 insecure_key
##
## Install edX
##
ssh -i insecure_key root@$IP cp /etc/apt/sources.list  /etc/apt/sources.list.bak
ssh -i insecure_key root@$IP sed -i 's/security.ubuntu.com/mirrors.ustc.edu.cn/g' /etc/apt/sources.list
ssh -i insecure_key root@$IP sed -i 's/archive.ubuntu.com/mirrors.ustc.edu.cn/g' /etc/apt/sources.list
ssh -i insecure_key root@$IP apt-get update &&  apt-get install -y build-essential software-properties-common python-software-properties curl git-core libxml2-dev libxslt1-dev libfreetype6-dev python-pip python-apt python-dev
ssh -i insecure_key root@$IP pip install --upgrade pip && pip install --upgrade virtualenv
ssh -i insecure_key root@$IP cd /configuration && pip install -r requirements.txt
ssh -i insecure_key root@$IP cd /configuration/playbooks && ansible-playbook -vv -c local -i "127.0.0.1," docker_lite.yml
##
## Push & commit
##
sudo docker stop $ID
sudo docker commit -m="init" -a="Jason Zhu" $ID fmyzjs/edx-lite-cn:alpha
sudo docker push fmyzjs/edx-lite-cn
