- name: Configure instance(s)
  hosts: all
  sudo: True
  gather_facts: True
  vars:
    migrate_db: 'yes'
    openid_workaround: true
    devstack: true
    disable_edx_services: true
    mongo_enable_journal: false
    mongo_create_users: true
    EDXAPP_NO_PREREQ_INSTALL: 0
    COMMON_MOTD_TEMPLATE: 'devstack_motd.tail.j2'
    COMMON_SSH_PASSWORD_AUTH: "yes"
    ENABLE_LEGACY_ORA: !!null
    EDX_ANSIBLE_DUMP_VARS: True
  vars_files:
    - "group_vars/devstack"
  roles:
    - edx_ansible
    - edxlocal
    - mongo
    - edxapp
    - oraclejdk
    - elasticsearch
    - forum
    - role: ora
      when: ENABLE_LEGACY_ORA
    - browsers
    - browsermob-proxy
    - local_dev
    - demo
    - role: analytics-api
      when: ANALYTICS_API_GIT_IDENTITY
